### ISSUE TITLE
config compatibility with twtxt

### ISSUE THREAD

**Issue by archusr** [mdom/txtnix#18]
It seems twtxt wants the hooks within quotes, whereas txtnix doesn't. [edit: not sure what's better, e.g. considering quoting for piping to curl etc.]

**Comment by mdom** [comment]
I would have to remove the quotes by myself as the library i use does not have any special quote handling. And i'm not even sure my goal should be to be compatible with twtxt. There are probably already some cases where i use the same configuration name with a different semantic. I even thought about switching to another configuration file syntax. I'll close this specific issue, but do not hesitate to point me to any other compatibility problems. If i can easily fix them, i will.

**Comment by archusr** [comment]
Thanks considering this. Hm, how about simply renaming the txtnix config file to its own name?

**Comment by mdom** [comment]
Yeah. I think it's time to do this!
